const resortModelData = [
    {
        name: 'Keystone',
        logo: 'https://images.vailresorts.com/image/upload/c_scale,dpr_1.0,f_auto,q_auto,w_1000/v1/Global/Logos/Resort%20Logos%20Fixed%20Width/New/Keystone_logo.png',
        passName: 'Epic',
        passLogo: 'https://mont-sainte-anne.com/wp-content/uploads/2018/08/epic_visual_logo.png',
        lat: '39.608665',
        long: '-105.943664',
    },
    {
        name: 'Eldora',
        logo: 'https://www.eldora.com/assets/eldora/images/site-logo-desktop-translucent.svg',
        passName: 'Ikon',
        passLogo: 'https://cms.coppercolorado.com/sites/copper/files/inline-images/Ikon_Logo_PNG-02.png',
        lat: '39.938273',
        long: '-105.582646',
    },
    {
        name: 'Vail',
        logo: 'https://d1aup3of1p0fq2.cloudfront.net/resort-logos/resort-logo-169.png',
        passName: 'Epic',
        passLogo: 'https://mont-sainte-anne.com/wp-content/uploads/2018/08/epic_visual_logo.png',
        lat: '39.607120',
        long: '-106.355058',
    },
    {
        name: 'Beaver Creek',
        logo: 'https://usskiandsnowboard.org/sites/default/files/partner-logos/2018-04/Beaver--Creek--Logo.png',
        passName: 'Epic',
        passLogo: 'https://mont-sainte-anne.com/wp-content/uploads/2018/08/epic_visual_logo.png',
        lat: '39.605394',
        long: '-106.516797',
    },
    {
        name: 'Crested Butte',
        logo: 'https://i0.wp.com/www.resortworkers.com/wp-content/uploads/2016/02/Crested-Butte-Resort-1.png?w=680&ssl=1',
        passName: 'Epic',
        passLogo: 'https://mont-sainte-anne.com/wp-content/uploads/2018/08/epic_visual_logo.png',
        lat: '38.900156',
        long: '-106.965094',
    },
    {
        name: 'Telluride',
        logo: 'https://static1.squarespace.com/static/5a3c4eaaccc5c565cc43d3e8/5a8373ee652dea6c8977a1d8/5a8373eef9619ad89ab5c042/1518564335791/TelSki-web.png?format=500w',
        passName: 'Epic',
        passLogo: 'https://mont-sainte-anne.com/wp-content/uploads/2018/08/epic_visual_logo.png',
        lat: '37.917198',
        long: '-107.837245',
    },
    {
        name: 'Aspen Snowmass',
        logo: 'https://images.ctfassets.net/ycpblqmln66n/4Jk51m4cFyUSiWgUSYgm0i/f3f73b6506cb7e1a474ff505439f9946/aspen-snowmass_2x.png',
        passName: 'Ikon',
        passLogo: 'https://cms.coppercolorado.com/sites/copper/files/inline-images/Ikon_Logo_PNG-02.png',
        lat: '39.212946',
        long: '-106.949854',
    },
    {
        name: 'Steamboat',
        logo: 'https://s3.amazonaws.com/shipsticks_partner_assets_production/uploads/05d44d45-2bc1-4a8c-bb9a-67743ed76343.png',
        passName: 'Ikon',
        passLogo: 'https://cms.coppercolorado.com/sites/copper/files/inline-images/Ikon_Logo_PNG-02.png',
        lat: '40.457436',
        long: '-106.804533',
    },
    {
        name: 'Winter Park',
        logo: 'https://seeklogo.com/images/W/winter-park-resort-logo-EC5745F402-seeklogo.com.png',
        passName: 'Ikon',
        passLogo: 'https://cms.coppercolorado.com/sites/copper/files/inline-images/Ikon_Logo_PNG-02.png',
        lat: '39.887104',
        long: '-105.762548',
    },
    {
        name: 'Copper Mountain',
        logo: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSDeaRXAq_rZLOUlnXQb2M1GF33AK6UD3IUN3A1bPRO3Mk5dvCq',
        passName: 'Ikon',
        passLogo: 'https://cms.coppercolorado.com/sites/copper/files/inline-images/Ikon_Logo_PNG-02.png',
        lat: '39.500176',
        long: '-106.145982',
    },
    {
        name: 'Eldora',
        logo: 'https://igniteadaptivesports.org/wp-content/uploads/2018/10/eldora-site-logo-desktop-1.svg',
        passName: 'Ikon',
        passLogo: 'https://cms.coppercolorado.com/sites/copper/files/inline-images/Ikon_Logo_PNG-02.png',
        lat: '39.937459',
        long: '-105.582636',
    },
    // {
    //     name: '',
    //     logo: '',
    //     passName: '',
    //     passLogo: 'https://cms.coppercolorado.com/sites/copper/files/inline-images/Ikon_Logo_PNG-02.png',
    //     lat: '',
    //     long: '',
    // },
    // {
    //     name: '',
    //     logo: '',
    //     passName: '',
    //     passLogo: '',
    //     lat: '',
    //     long: '',
    // },
    // {
    //     name: '',
    //     logo: '',
    //     passName: '',
    //     passLogo: '',
    //     lat: '',
    //     long: '',
    // },
    // {
    //     name: '',
    //     logo: '',
    //     passName: '',
    //     passLogo: '',
    //     lat: '',
    //     long: '',
    // },
    // {
    //     name: '',
    //     logo: '',
    //     passName: '',
    //     passLogo: '',
    //     lat: '',
    //     long: '',
    // },
    // {
    //     name: '',
    //     logo: '',
    //     passName: '',
    //     passLogo: '',
    //     lat: '',
    //     long: '',
    // },
]